testdata/in/break_in_catch.nen:3:3: invalid break outside a loop
