testdata/in/continue_outside_loop.nen:2:2: invalid continue outside a loop
